/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as SetupRouteRouteImport } from './routes/setup/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppDevRouteImport } from './routes/_app/dev'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStatusRouteImport } from './routes/_app/status'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as Setup1OllamaRouteImport } from './routes/setup/1-ollama'
import { Route as Setup2OcrModelRouteImport } from './routes/setup/2-ocr-model'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRouteRoute = SetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevRoute = AppDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRouteRoute,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRouteRoute,
} as any)
const Setup1OllamaRoute = Setup1OllamaRouteImport.update({
  id: '/1-ollama',
  path: '/1-ollama',
  getParentRoute: () => SetupRouteRoute,
} as any)
const Setup2OcrModelRoute = Setup2OcrModelRouteImport.update({
  id: '/2-ocr-model',
  path: '/2-ocr-model',
  getParentRoute: () => SetupRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/setup': typeof SetupRouteRouteWithChildren
  '/dev': typeof AppDevRoute
  '/settings': typeof AppSettingsRoute
  '/status': typeof AppStatusRoute
  '/setup/1-ollama': typeof Setup1OllamaRoute
  '/setup/2-ocr-model': typeof Setup2OcrModelRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRoutesByTo {
  '/dev': typeof AppDevRoute
  '/settings': typeof AppSettingsRoute
  '/status': typeof AppStatusRoute
  '/setup/1-ollama': typeof Setup1OllamaRoute
  '/setup/2-ocr-model': typeof Setup2OcrModelRoute
  '/': typeof AppIndexRoute
  '/setup': typeof SetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/setup': typeof SetupRouteRouteWithChildren
  '/_app/dev': typeof AppDevRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/status': typeof AppStatusRoute
  '/setup/1-ollama': typeof Setup1OllamaRoute
  '/setup/2-ocr-model': typeof Setup2OcrModelRoute
  '/_app/': typeof AppIndexRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/dev'
    | '/settings'
    | '/status'
    | '/setup/1-ollama'
    | '/setup/2-ocr-model'
    | '/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dev'
    | '/settings'
    | '/status'
    | '/setup/1-ollama'
    | '/setup/2-ocr-model'
    | '/'
    | '/setup'
  id:
    | '__root__'
    | '/_app'
    | '/setup'
    | '/_app/dev'
    | '/_app/settings'
    | '/_app/status'
    | '/setup/1-ollama'
    | '/setup/2-ocr-model'
    | '/_app/'
    | '/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SetupRouteRoute: typeof SetupRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dev': {
      id: '/_app/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AppDevRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/status': {
      id: '/_app/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/1-ollama': {
      id: '/setup/1-ollama'
      path: '/1-ollama'
      fullPath: '/setup/1-ollama'
      preLoaderRoute: typeof Setup1OllamaRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/2-ocr-model': {
      id: '/setup/2-ocr-model'
      path: '/2-ocr-model'
      fullPath: '/setup/2-ocr-model'
      preLoaderRoute: typeof Setup2OcrModelRouteImport
      parentRoute: typeof SetupRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDevRoute: typeof AppDevRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatusRoute: typeof AppStatusRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDevRoute: AppDevRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatusRoute: AppStatusRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface SetupRouteRouteChildren {
  Setup1OllamaRoute: typeof Setup1OllamaRoute
  Setup2OcrModelRoute: typeof Setup2OcrModelRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteRouteChildren: SetupRouteRouteChildren = {
  Setup1OllamaRoute: Setup1OllamaRoute,
  Setup2OcrModelRoute: Setup2OcrModelRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteRouteWithChildren = SetupRouteRoute._addFileChildren(
  SetupRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  SetupRouteRoute: SetupRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
